apiVersion: v2
name: sketch-map-tool
description: A Helm chart for SketchMapTool
icon: https://heigit.org/wp-content/uploads/2025/11/SketchMap_Logo.svg
type: application

sources:
  - https://github.com/GIScience/sketch-map-tool
maintainers:
  - name: HeiGIT
    url: https://heigit.org/

dependencies:
  - name: postgres
    repository: https://groundhog2k.github.io/helm-charts
    condition: postgres.enabled
    version: 1.6.1
  - name: redis
    repository: https://groundhog2k.github.io/helm-charts
    condition: redis.enabled
    version: 2.3.0

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2025.11.28"
