apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sketch-map-tool.fullname" . }}-flask
  labels:
    {{- include "sketch-map-tool.labels" . | nindent 4 }}
    app.kubernetes.io/component: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sketch-map-tool.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: flask
  template:
    metadata:
      labels:
        {{- include "sketch-map-tool.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: flask
    spec:
      containers:
        - name: flask
          image: "{{ .Values.flask.image.repository }}:{{ .Values.flask.image.tag }}"
          command:
            - waitress-serve
            - sketch_map_tool.routes:app
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.flask.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.flask.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
