data-dir = "/some/absolute/path"
user-agent = "sketch-map-tool"
broker-url = "redis://localhost:6379"
result-backend = "db+postgresql://smt:smt@localhost:5432"
data-store = "redis://localhost:6379"
wms-url-osm = "https://maps.heigit.org/osm-carto/service?SERVICE=WMS&VERSION=1.1.1"
wms-layers-osm = "heigit:osm-carto@2xx"
wms-url-esri-world-imagery = "https://maps.heigit.org/sketch-map-tool/service?SERVICE=WMS&VERSION=1.1.1"
wms-layers-esri-world-imagery = "world_imagery"
wms-read-timeout = 600
max-nr-simultaneous-uploads = 100
neptune_api_token = "h0dHBzOi8aHR06E0Z...jMifQ"
neptune_project = "HeiGIT/SketchMapTool"
neptune_model_id_yolo_osm_obj = "SMT-OSM-6"
neptune_model_id_yolo_esri_obj = "SMT-ESRI-1"
neptune_model_id_yolo_osm_cls = "SMT-CLR-1"
neptune_model_id_yolo_esri_cls = "SMT-CLR-3"
neptune_model_id_sam = "SMT-SAM-1"
model_type_sam = "vit_b"
esri-api-key = ""
