apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sketch-map-tool.fullname" . }}
  labels:
    {{- include "sketch-map-tool.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sketch-map-tool.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "sketch-map-tool.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery
    spec:
      containers:
        - name: celery
          image: "{{ .Values.celery.image.repository }}:{{ .Values.celery.image.tag }}"
          command:
            - celery
            - --app
            - sketch_map_tool.tasks
            - worker
            - --beat
            - --concurrency
            - "6"
            - --loglevel
            - INFO
            - -E
          {{- with .Values.celery.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: weights
              mountPath: /app/weights
      restartPolicy: Always
      volumes:
        - name: weights
          persistentVolumeClaim:
            claimName: {{ include "sketch-map-tool.fullname" . }}-celery-weights
