apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sketch-map-tool.fullname" . }}-celery
  labels:
    {{- include "sketch-map-tool.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sketch-map-tool.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "sketch-map-tool.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery
    spec:
      initContainers:
        - name: download-weights
          image: debian:stable-slim
          command:
            - sh
            - -c
          args:
            - "apt-get update && apt-get install -y wget && wget --timestamping --directory-prefix /data/weights {{ .Values.celery.weightsSourceUrl.osm }} {{ .Values.celery.weightsSourceUrl.esri }} {{ .Values.celery.weightsSourceUrl.cls }}"
          volumeMounts:
            - name: weights
              mountPath: /data/weights
      containers:
        - name: celery
          image: "{{ .Values.celery.image.repository }}:{{ .Values.celery.image.tag | default .Chart.AppVersion }}"
          command:
            - celery
            - --app
            - sketch_map_tool.tasks
            - worker
            - --beat
            - --concurrency
            - "6"
            - --loglevel
            - INFO
            - -E
          env:
            {{- include "sketch-map-tool.postgresVars" . | nindent 12 }}
            {{- include "sketch-map-tool.redisVars" . | nindent 12 }}
          {{- with .Values.celery.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: weights
              mountPath: /app/weights
          {{- if .Values.customConfig }}
            - name: config
              mountPath: /app/config
          {{- end }}
      {{- with .Values.celery.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      volumes:
        - name: weights
          persistentVolumeClaim:
            claimName: {{ include "sketch-map-tool.fullname" . }}-celery-weights
        {{- if .Values.customConfig }}
        - name: config
          secret:
            secretName: {{ include "sketch-map-tool.fullname" . }}-custom-config
        {{- end }}
