apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sketch-map-tool.fullname" . }}-celery-weights
  labels:
    {{- include "sketch-map-tool.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery
spec:
  accessModes:
  {{- range .Values.celery.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.celery.persistence.size | quote }}
  {{- if .Values.celery.persistence.storageClassName }}
  storageClassName: {{ .Values.celery.persistence.storageClassName }}
  {{- end }}
